# Generated by Django 3.2.6 on 2021-08-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
